services:
  - type: web
    name: survai
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "./bin/render-build.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: survai-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: survai-db
    plan: free
    plan: free
